config/routes.rb
Rails.application.routes.draw do
  resources :carts_products
  resources :addresses_users
  resources :order_picks
  resources :credit_cards
  resources :debit_cards
  resources :tickets
  resources :pixes
  resources :payments
  resources :order_products
  resources :orders
  resources :carts
  resources :positions
  resources :stock_products
  resources :invoices
  resources :suppliers
  resources :stocks
  resources :stores
  resources :addresses
  resources :products
  resources :categories
  resources :users
  get "home/index"  
  root to: "home#index"
end

app/models/address.rb
class Address < ApplicationRecord
    has_one  :store
    has_and_belongs_to_many :users
end

app/models/admin.rb
class Admin < Employee
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :products, through: :carts_product
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :products
end

app/models/client.rb
class Client < User
end

app/models/credit_card.rb
class CreditCard < Payment
end

app/models/debit_card.rb
class DebitCard < Payment
end

app/models/employee.rb
class Employee < User
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :supplier
  belongs_to :user
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :user
    has_one :invoice
end

app/models/order_pick.rb
class OrderPick < ApplicationRecord
  belongs_to :position
  belongs_to :order
  belongs_to :user
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :order
end

app/models/pix.rb
class Pix < Payment
end

app/models/position.rb
class Position < ApplicationRecord
  belongs_to :stock_product
  belongs_to :stock
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :carts, through: :carts_product
end

app/models/stock.rb
class Stock < ApplicationRecord
  belongs_to :store
end

app/models/store.rb
class Store < Supplier
  belongs_to :address
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  belongs_to :address
  has_many :invoices
end

app/models/ticket.rb
class Ticket < Payment
end

app/models/user.rb
class User < ApplicationRecord
    has_and_belongs_to_many :addresses
    has_many :orders
    has_one :cart
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: %i[ show edit update destroy ]

  # GET /stores or /stores.json
  def index
    @stores = Store.all
  end

  # GET /stores/1 or /stores/1.json
  def show
  end

  # GET /stores/new
  def new
    @store = Store.new
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores or /stores.json
  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to store_url(@store), notice: "Store was successfully created." }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1 or /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to store_url(@store), notice: "Store was successfully updated." }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1 or /stores/1.json
  def destroy
    @store.destroy

    respond_to do |format|
      format.html { redirect_to stores_url, notice: "Store was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def store_params
      params.require(:store).permit(:name, :cnpj, :address_id)
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_form.html.erb
<%= form_with(model: store) do |form| %>
  <% if store.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
        <% store.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :cnpj, style: "display: block" %>
    <%= form.text_field :cnpj %>
  </div>

  <div>
    <%= form.label :address_id, style: "display: block" %>
    <%= form.text_field :address_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/stores/_store.html.erb
<div id="<%= dom_id store %>">
  <p>
    <strong>Name:</strong>
    <%= store.name %>
  </p>

  <p>
    <strong>Cnpj:</strong>
    <%= store.cnpj %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= store.address_id %>
  </p>

</div>

app/views/stores/edit.html.erb
<h1>Editing store</h1>

<%= render "form", store: @store %>

<br>

<div>
  <%= link_to "Show this store", @store %> |
  <%= link_to "Back to stores", stores_path %>
</div>

app/views/stores/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Stores</h1>

<div id="stores">
  <% @stores.each do |store| %>
    <%= render store %>
    <p>
      <%= link_to "Show this store", store %>
    </p>
  <% end %>
</div>

<%= link_to "New store", new_store_path %>

app/views/stores/new.html.erb
<h1>New store</h1>

<%= render "form", store: @store %>

<br>

<div>
  <%= link_to "Back to stores", stores_path %>
</div>

app/views/stores/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @store %>

<div>
  <%= link_to "Edit this store", edit_store_path(@store) %> |
  <%= link_to "Back to stores", stores_path %>

  <%= button_to "Destroy this store", @store, method: :delete %>
</div>