config/routes.rb
Rails.application.routes.draw do
  resources :carts_products
  resources :addresses_users
  resources :order_picks
  resources :credit_cards
  resources :debit_cards
  resources :tickets
  resources :pixes
  resources :payments
  resources :order_products
  resources :orders
  resources :carts
  resources :positions
  resources :stock_products
  resources :invoices
  resources :suppliers
  resources :stocks
  resources :stores
  resources :addresses
  resources :products
  resources :categories
  resources :users
  get "home/index"  
  root to: "home#index"
end

app/models/address.rb
class Address < ApplicationRecord
    has_one  :store
    has_and_belongs_to_many :users
end

app/models/admin.rb
class Admin < Employee
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :products, through: :carts_product
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :products
end

app/models/client.rb
class Client < User
end

app/models/credit_card.rb
class CreditCard < Payment
end

app/models/debit_card.rb
class DebitCard < Payment
end

app/models/employee.rb
class Employee < User
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :supplier
  belongs_to :user
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :user
    has_one :invoice
end

app/models/order_pick.rb
class OrderPick < ApplicationRecord
  belongs_to :position
  belongs_to :order
  belongs_to :user
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :order
end

app/models/pix.rb
class Pix < Payment
end

app/models/position.rb
class Position < ApplicationRecord
  belongs_to :stock_product
  belongs_to :stock
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :carts, through: :carts_product
end

app/models/stock.rb
class Stock < ApplicationRecord
  belongs_to :store
end

app/models/store.rb
class Store < Supplier
  belongs_to :address
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  belongs_to :address
  has_many :invoices
end

app/models/ticket.rb
class Ticket < Payment
end

app/models/user.rb
class User < ApplicationRecord
    has_and_belongs_to_many :addresses
    has_many :orders
    has_one :cart
end

app/controllers/credit_cards_controller.rb
class CreditCardsController < ApplicationController
  before_action :set_credit_card, only: %i[ show edit update destroy ]

  # GET /credit_cards or /credit_cards.json
  def index
    @credit_cards = CreditCard.all
  end

  # GET /credit_cards/1 or /credit_cards/1.json
  def show
  end

  # GET /credit_cards/new
  def new
    @credit_card = CreditCard.new
  end

  # GET /credit_cards/1/edit
  def edit
  end

  # POST /credit_cards or /credit_cards.json
  def create
    @credit_card = CreditCard.new(credit_card_params)

    respond_to do |format|
      if @credit_card.save
        format.html { redirect_to credit_card_url(@credit_card), notice: "Credit card was successfully created." }
        format.json { render :show, status: :created, location: @credit_card }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @credit_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /credit_cards/1 or /credit_cards/1.json
  def update
    respond_to do |format|
      if @credit_card.update(credit_card_params)
        format.html { redirect_to credit_card_url(@credit_card), notice: "Credit card was successfully updated." }
        format.json { render :show, status: :ok, location: @credit_card }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @credit_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /credit_cards/1 or /credit_cards/1.json
  def destroy
    @credit_card.destroy

    respond_to do |format|
      format.html { redirect_to credit_cards_url, notice: "Credit card was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_credit_card
      @credit_card = CreditCard.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def credit_card_params
      params.require(:credit_card).permit(:key)
    end
end

app/helpers/credit_cards_helper.rb
module CreditCardsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/credit_cards/_credit_card.html.erb
<div id="<%= dom_id credit_card %>">
  <p>
    <strong>Key:</strong>
    <%= credit_card.key %>
  </p>

</div>

app/views/credit_cards/_form.html.erb
<%= form_with(model: credit_card) do |form| %>
  <% if credit_card.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(credit_card.errors.count, "error") %> prohibited this credit_card from being saved:</h2>

      <ul>
        <% credit_card.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :key, style: "display: block" %>
    <%= form.text_field :key %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/credit_cards/edit.html.erb
<h1>Editing credit card</h1>

<%= render "form", credit_card: @credit_card %>

<br>

<div>
  <%= link_to "Show this credit card", @credit_card %> |
  <%= link_to "Back to credit cards", credit_cards_path %>
</div>

app/views/credit_cards/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Credit cards</h1>

<div id="credit_cards">
  <% @credit_cards.each do |credit_card| %>
    <%= render credit_card %>
    <p>
      <%= link_to "Show this credit card", credit_card %>
    </p>
  <% end %>
</div>

<%= link_to "New credit card", new_credit_card_path %>

app/views/credit_cards/new.html.erb
<h1>New credit card</h1>

<%= render "form", credit_card: @credit_card %>

<br>

<div>
  <%= link_to "Back to credit cards", credit_cards_path %>
</div>

app/views/credit_cards/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @credit_card %>

<div>
  <%= link_to "Edit this credit card", edit_credit_card_path(@credit_card) %> |
  <%= link_to "Back to credit cards", credit_cards_path %>

  <%= button_to "Destroy this credit card", @credit_card, method: :delete %>
</div>